apiVersion: v2
name: ${{ values.name }}
description: Helm chart for ${{ values.name }} Java service
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: ${{ values.owner }}
    email: ${{ values.owner }}@company.com