apiVersion: v2
name: backstage
description: A Helm chart for Backstage Internal Developer Platform
type: application
version: 0.1.0
appVersion: '1.0.0'
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
